name: Deploy Production

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build --platform linux/amd64 -t hiepsadoi/gymlord:v0 .
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Push docker image
              run: docker push hiepsadoi/gymlord:v0
            - name: Notify Telegram success
              if: success()
              uses: appleboy/telegram-action@v0.1.1
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      ✅ Build SUCCESS
                      ${{github.actor }} created commit:
                      Commit message: ${{ github.event.commits[0].message }}
                      Repository: ${{ github.repository }}
                      Branch: ${{ github.ref_name }}
                      See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            - name: Notify Telegram Failure
              if: failure()
              uses: appleboy/telegram-action@v0.1.1
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      ❌ BUILD FAILURE
                      ${{github.actor }} created commit:
                      Commit message: ${{ github.event.commits[0].message }}
                      Repository: ${{ github.repository }}
                      Branch: ${{ github.ref_name }}
                      See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST_PRODUCTION }}
                  username: ${{ secrets.USERNAME_PRODUCTION }}
                  password: ${{ secrets.PASSWORD_PRODUCTION }}
                  port: ${{ secrets.PORT_PRODUCTION }}
                  script: |
                      cd ~/gymlord
                      docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                      docker pull hiepsadoi/gymlord:v0
                      docker compose -f docker-compose.prod.yml up -d
            - name: Notify Telegram Deploy Success
              if: success()
              uses: appleboy/telegram-action@v0.1.1
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      ✅ DEPLOY SUCCESS
                      ${{github.actor }} created commit:
                      Commit message: ${{ github.event.commits[0].message }}
                      Repository: ${{ github.repository }}
                      Branch: ${{ github.ref_name }}
                      See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            - name: Notify Telegram Deploy Failure
              if: failure()
              uses: appleboy/telegram-action@v0.1.1
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      ❌ DEPLOY FAILURE
                      ${{github.actor }} created commit:
                      Commit message: ${{ github.event.commits[0].message }}
                      Repository: ${{ github.repository }}
                      Branch: ${{ github.ref_name }}
                      See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
